(TeX-add-style-hook "Usinglme"
 (lambda ()
    (LaTeX-add-bibliographies
     "Usinglme")
    (LaTeX-add-labels
     "sec:intro"
     "sec:similarities"
     "eqn:oneLevel"
     "sec:differences"
     "sec:data"
     "sec:nested"
     "sec:generalApproach"
     "sec:contrasts"
     "sec:AvgDailyGain"
     "fig:adg1"
     "sec:BIB"
     "fig:bib1"
     "sec:Bond"
     "sec:Cultivation"
     "fig:adg1"
     "fig:adg1"
     "sec:Demand"
     "fig:demand1"
     "sec:Genetics"
     "sec:HR"
     "fig:hr1"
     "sec:Mississippi"
     "fig:mississippi1"
     "sec:Multilocation"
     "sec:PBIB"
     "sec:SIMS")
    (TeX-add-symbols
     "s"
     "R")
    (TeX-run-style-hooks
     "natbib"
     "authoryear"
     "round"
     "myVignette"
     "Sweave"
     "latex2e"
     "art12"
     "article"
     "12pt")))

